### ISSUE TITLE
"configuring net servers to use SSL" points to an id that does not exist.

### ISSUE THREAD

**Issue by zerkz** [vert-x3/vertx-web-site#71] opened 2015-06-17 16:18 UTC
Seen at http://vert-x3.github.io/docs/vertx-core/java/#_using_https_with_vert_x

![image](https://cloud.githubusercontent.com/assets/1448099/8212633/aa69269e-14ea-11e5-8d22-1ea9fe203325.png)

The documentation for Net servers, particularly with SSL seems to exist. The ID this anchor points to just doesn't.

**Comment by cescoffier** [comment] 2015-06-17 17:18
The issue is in vertx-core.

Actually, two anchors are missing:

* Element missing #security_notes
* Element missing #netserver_ssl

**Comment by zerkz** [comment] 2015-06-17 17:25
Looks like #netserver_ssl should be #ssl 

Not sure about the other one.

**Comment by cescoffier** [comment] 2015-06-17 17:40
Closing this one, it will be fixed by https://github.com/eclipse/vert.x/pull/1079. 
Thanks for reporting.

**Closed by cescoffier** 2015-06-17 17:40 UTC
